spring:
  application:
    name: ecofarming

  profiles:
    active: local  # 기본 프로파일 설정

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update  # 기본값, 필요시 변경 가능

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB