spring:
  datasource:
    url: jdbc:mysql://j11a101.p.ssafy.io:3306/ecofarming
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  file:
    upload-dir: /home/ubuntu/uploads
  redis:
    host: j11a101.p.ssafy.io
    port: 6379
    password: 1234
    timeout: 6000ms
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
