spring:
  datasource:
    url: jdbc:mysql://j11a101.p.ssafy.io:3306/ecofarming
    username: root
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
  redis:
    host: j11a101.p.ssafy.io
    port: 6379
    password: 1234
    timeout: 6000ms

file:
  upload-dir: /home/ubuntu/uploads

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
