spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecofarming
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
file:
  upload-dir: C:\Users\SSAFY\Desktop

mattermost:
  webhook:
    url: https://meeting.ssafy.com/hooks/cmxabk41mbgjjd6n9dbhypy67y
