spring:
  datasource:
    url: jdbc:mysql://j11a101.p.ssafy.io:3306/ecofarming  # 도메인 넣어야함
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  file:
    upload-dir: /home/ubuntu/uploads
management:
  endpoints:
    web:
      exposure:
        include: "*"